[package]
name = "python-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = "0.22.0"
# outlines-core = { path = "../../outlines-core" }

[profile.release-lto]
inherits = "release"
lto = true

[lib]
name = "_lib"
crate-type = ["cdylib"]
path = "rust/lib.rs"
