name: Rust Criterion Benchmarks

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, labeled]
  workflow_dispatch:

env:
  BENCHMARKS_OUTPUT: ${{ github.workspace }}/benchmarks_output
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  RUSTFLAGS: ""

permissions:
  deployments: write
  contents: write

jobs:
  Criterion:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'run-benchmarks') || github.event_name == 'push' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # Needed to provide cargo bench compatible output
      - name: Install cargo-criterion
        run: cargo install cargo-criterion

      - name: Download previous benchmark data
        uses: actions/cache/restore@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Cat previous data
        run: cat ./cache/benchmark-data.json

      - name: Run benchmarks
        run: cargo criterion --output-format bencher |& tee benchmarks.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        if: github.event_name == 'push'
        with:
          tool: 'cargo'
          output-file-path: benchmarks.txt
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: cb

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        if: github.event_name == 'pull_request'
        with:
          tool: 'cargo'
          output-file-path: benchmarks.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          auto-push: false

      - name: Upload new benchmark data
        if: github.event_name == 'push'
        uses: actions/cache/save@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
